apiVersion: v2
name: billing
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: postgresql
  version: 12.2.6
  repository: https://charts.bitnami.com/bitnami
