---
- name: Master provision
  hosts: master

  tasks:
  - name: Set alias ll
    replace:
      path: /home/vagrant/.bashrc
      regexp: "^#alias ll='ls -l'$"
      replace: "alias ll='ls -la'"

  - name: Set colors
    replace:
      path: /home/vagrant/.bashrc
      regexp: "^#force_color_prompt=yes$"
      replace: "force_color_prompt=yes"

- name: Slave provision
  hosts: slave

  tasks:
  - name: Set alias ll
    replace:
      path: /home/vagrant/.bashrc
      regexp: "^#alias ll='ls -l'$"
      replace: "alias ll='ls -la'"
    register: replace_output


  - name: Hello world
    debug:
      var: replace_output

  - name: Print Linux version
    shell: echo $(cat /etc/os-release) >testfile
    register: shell_output
    args:
      chdir: /home/vagrant
      creates: testfile

  - name: read shell_output
    debug:
      msg: "shell output is {{ shell_output }}"

  - name: read shell_output from var
    debug:
      var: shell_output
