Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8s"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus   = 1
    end

    config.vm.define "slave1.puppet" do |host|
        host.vm.network "private_network", ip: "192.168.50.10"
        host.vm.hostname = "slave1.puppet"
    end

    config.vm.define "slave2.puppet" do |host|
        host.vm.network "private_network", ip: "192.168.50.15"
        host.vm.hostname = "slave2.puppet"
    end

    config.vm.define "minecraft.puppet", primary: true do |host|
        host.vm.network "private_network", ip: "192.168.50.20"
        host.vm.hostname = "minecraft.puppet"
        host.vm.provider("virtualbox") { |vb| vb.memory = 1024 }
    end

    config.vm.define "master.puppet", primary: true do |host|
        host.vm.network "private_network", ip: "192.168.50.5"
        host.vm.hostname = "master.puppet"
        host.vm.provider("virtualbox") { |vb| vb.memory = 1024 }
        
        host.vm.provision "file", source: ".vagrant/machines/slave1.puppet/virtualbox/private_key", destination: "/home/vagrant/.ssh/private_key_slave1"
        host.vm.provision "file", source: ".vagrant/machines/slave2.puppet/virtualbox/private_key", destination: "/home/vagrant/.ssh/private_key_slave2"
        host.vm.provision "file", source: ".vagrant/machines/minecraft.puppet/virtualbox/private_key", destination: "/home/vagrant/.ssh/private_key_minecraft"
        
        host.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.limit = 'all'
            ansible.inventory_path = "inventory"
        end

    end
end
