---
- name: Test play
  hosts: all

  tasks:
  - name: Hello world
    debug:
      msg: "Hello, world!"

  - name: Create file
    file:
      path: /vagrant/test.txt
      state: touch

  - name: add new line1
    lineinfile:
      path: /vagrant/test.txt
      line: new line

  - name: add new line2
    lineinfile:
      path: /vagrant/test.txt
      line: new line

  # - name: add new line3
  #   shell: echo "new line" >> /vagrant/test.txt

