---
- name: Tasks play
  hosts: slave1
  vars:
    ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38663966363666643264616235656236333839363066343930383438313538383733346431376136
          3839656338396261366666393332323532646338363038300a616237666539646534656361343163
          38393738383535333533623032626261616531383539626265633733366163383334353235306533
          3365313566353939320a346630653034633131373764343431373130393766363937346563353866
          6534
  # roles:
  #   - role: wcg
  #     become: yes

  tasks:
  - name: Create directory /home/vagrant/read
    file:
      path: "{{ item.value.path }}"
      state: directory
      mode: "{{ item.value.mode }}"
      owner: "{{ item.value.owner }}"
      group: "{{ item.value.owner }}"
    with_dict:
    - "{{ directories }}"

  # - name: Install packages
  #   become: yes
  #   apt:
  #     name: 
  #     - apache2
  #     - vim
  #     - mc
  #     state: present
  #     update_cache: true
  #   when: ansible_facts.os_family == 'Debian' and ansible_facts.distribution_major_version >= "11"

  # - name: Install packages
  #   become: yes
  #   dnf:
  #     name: 
  #     - httpd
  #     - vim
  #     - mc
  #     state: present
  #     update_cache: true
  #   when: ansible_facts.os_family == 'RedHat'

  - name: start and enable apache
    become: true
    service:
      name: httpd
      state: started
      enabled: true
    delegate_to: slave2

  # - name: Create file
  #   become: yes
  #   copy:
  #     dest: /var/www/html/index.html
  #     content: |
  #       Mem size is: {{ ansible_facts.memtotal_mb }} 
  #       disk size is: {{ ansible_facts.mounts[0].size_total }}



