version: '2.4'
services:
  wcg1:
    image: wcg:small
    ports:
    - "8888:8888"
    depends_on: 
      wcg2:
        condition: service_healthy

  wcg2:
    image: wcg:big
    ports:
    - "8890:8888"
    healthcheck:
      test: curl -f https://localhost:8888
      interval: 10s 
      timeout: 10s 
      retries: 3
      start_period: 5s