apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development

  source:
    repoURL: https://github.com/Fenikks/devops-files-23.08.git
    targetRevision: master
    path: 15-helm/files/demo

    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      # parameters:
      # - name: "service.port"
      #   value: "9090"
      # - name: "replicas"
      #   value: "4"

      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      # valueFiles:
      # - values-dev.yaml

      # Values file as block file
      # values: |
      #   replicas: 3

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true