apiVersion: v1
kind: Pod
metadata:
  name: api-server
spec:
  containers:
  - name: server
    image: api-server:1.0

  - name: client
    image: feniks/ubuntu-netbox
    command: ["/bin/sh"]
    args: ["-c", "while true; do curl -s http://localhost:8080/date; sleep 2; done"]